# Used as inspiration: https://github.com/mvdan/github-actions-golang

name: Tests

on:
  push:

jobs:

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check